// <auto-generated />
using System;
using CSMatchesManager.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSMatchesManager.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116195209_Final3")]
    partial class Final3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSMatchesManager.DAL.Entities.Matches", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tournament_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("team1_Rounds")
                        .HasColumnType("int");

                    b.Property<int>("team2_Rounds")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("CSMatchesManager.DAL.Entities.Players", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Firepower")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("KD")
                        .HasColumnType("real");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("Sniping")
                        .HasColumnType("int");

                    b.Property<int>("Team_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Team_id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CSMatchesManager.DAL.Entities.Rewards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cologne")
                        .HasColumnType("int");

                    b.Property<int>("ESL")
                        .HasColumnType("int");

                    b.Property<int>("Grandslam")
                        .HasColumnType("int");

                    b.Property<int>("HLTV_TOP_1")
                        .HasColumnType("int");

                    b.Property<int>("Katowice")
                        .HasColumnType("int");

                    b.Property<int>("Majors")
                        .HasColumnType("int");

                    b.Property<int>("Player_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Player_id")
                        .IsUnique();

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("CSMatchesManager.DAL.Entities.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AVGDamage")
                        .HasColumnType("real");

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<int>("HSRate")
                        .HasColumnType("int");

                    b.Property<int>("Kills")
                        .HasColumnType("int");

                    b.Property<int>("Match_id")
                        .HasColumnType("int");

                    b.Property<int>("Player_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Match_id");

                    b.HasIndex("Player_id");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("CSMatchesManager.DAL.Entities.Teams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Foundingdate")
                        .HasColumnType("date");

                    b.Property<int>("MajorWon")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("CSMatchesManager.DAL.Entities.Teams_Match", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MatchID")
                        .HasColumnType("int");

                    b.Property<int>("Team1_id")
                        .HasColumnType("int");

                    b.Property<int>("Team2_id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MatchID");

                    b.HasIndex("Team1_id");

                    b.HasIndex("Team2_id");

                    b.ToTable("Teams_Matches");
                });

            modelBuilder.Entity("CSMatchesManager.DAL.Entities.Players", b =>
                {
                    b.HasOne("CSMatchesManager.DAL.Entities.Teams", "Team")
                        .WithMany("Players")
                        .HasForeignKey("Team_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CSMatchesManager.DAL.Entities.Rewards", b =>
                {
                    b.HasOne("CSMatchesManager.DAL.Entities.Players", "Player")
                        .WithOne("Rewards")
                        .HasForeignKey("CSMatchesManager.DAL.Entities.Rewards", "Player_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CSMatchesManager.DAL.Entities.Statistic", b =>
                {
                    b.HasOne("CSMatchesManager.DAL.Entities.Matches", "Match")
                        .WithMany("Stats")
                        .HasForeignKey("Match_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSMatchesManager.DAL.Entities.Players", "Player")
                        .WithMany("Statistics")
                        .HasForeignKey("Player_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CSMatchesManager.DAL.Entities.Teams_Match", b =>
                {
                    b.HasOne("CSMatchesManager.DAL.Entities.Matches", "Matches")
                        .WithMany("Teams_Matches")
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSMatchesManager.DAL.Entities.Teams", "Team1")
                        .WithMany("Team1_Matches")
                        .HasForeignKey("Team1_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSMatchesManager.DAL.Entities.Teams", "Team2")
                        .WithMany("Team2_Matches")
                        .HasForeignKey("Team2_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matches");

                    b.Navigation("Team1");

                    b.Navigation("Team2");
                });

            modelBuilder.Entity("CSMatchesManager.DAL.Entities.Matches", b =>
                {
                    b.Navigation("Stats");

                    b.Navigation("Teams_Matches");
                });

            modelBuilder.Entity("CSMatchesManager.DAL.Entities.Players", b =>
                {
                    b.Navigation("Rewards")
                        .IsRequired();

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("CSMatchesManager.DAL.Entities.Teams", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Team1_Matches");

                    b.Navigation("Team2_Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
